server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yoaotu_template?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: Dya110699++
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000